/**
 * This class is generated by jOOQ
 */
package model.persistence.jooq;

/**
 * This class is generated by jOOQ.
 *
 * A class modelling foreign key relationships between tables of the <code>crawler</code> 
 * schema
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.1.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.Identity<model.persistence.jooq.tables.records.CrawledRecord, java.lang.Integer> IDENTITY_CRAWLED = Identities0.IDENTITY_CRAWLED;
	public static final org.jooq.Identity<model.persistence.jooq.tables.records.DataRecord, java.lang.Integer> IDENTITY_DATA = Identities0.IDENTITY_DATA;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<model.persistence.jooq.tables.records.CrawledRecord> KEY_CRAWLED_PRIMARY = UniqueKeys0.KEY_CRAWLED_PRIMARY;
	public static final org.jooq.UniqueKey<model.persistence.jooq.tables.records.DataRecord> KEY_DATA_PRIMARY = UniqueKeys0.KEY_DATA_PRIMARY;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 extends org.jooq.impl.AbstractKeys {
		public static org.jooq.Identity<model.persistence.jooq.tables.records.CrawledRecord, java.lang.Integer> IDENTITY_CRAWLED = createIdentity(model.persistence.jooq.tables.Crawled.CRAWLED, model.persistence.jooq.tables.Crawled.CRAWLED.IDCRAWLED);
		public static org.jooq.Identity<model.persistence.jooq.tables.records.DataRecord, java.lang.Integer> IDENTITY_DATA = createIdentity(model.persistence.jooq.tables.Data.DATA, model.persistence.jooq.tables.Data.DATA.IDDATA);
	}

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<model.persistence.jooq.tables.records.CrawledRecord> KEY_CRAWLED_PRIMARY = createUniqueKey(model.persistence.jooq.tables.Crawled.CRAWLED, model.persistence.jooq.tables.Crawled.CRAWLED.IDCRAWLED);
		public static final org.jooq.UniqueKey<model.persistence.jooq.tables.records.DataRecord> KEY_DATA_PRIMARY = createUniqueKey(model.persistence.jooq.tables.Data.DATA, model.persistence.jooq.tables.Data.DATA.IDDATA);
	}
}
