/**
 * This class is generated by jOOQ
 */
package model.persistence.jooq;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in crawler
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table crawler.crawled
	 */
	public static final model.persistence.jooq.tables.Crawled CRAWLED = model.persistence.jooq.tables.Crawled.CRAWLED;

	/**
	 * The table crawler.data
	 */
	public static final model.persistence.jooq.tables.Data DATA = model.persistence.jooq.tables.Data.DATA;
}
