/**
 * This class is generated by jOOQ
 */
package model.persistence.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Crawled extends org.jooq.impl.TableImpl<model.persistence.jooq.tables.records.CrawledRecord> {

	private static final long serialVersionUID = -83469968;

	/**
	 * The singleton instance of <code>crawler.crawled</code>
	 */
	public static final model.persistence.jooq.tables.Crawled CRAWLED = new model.persistence.jooq.tables.Crawled();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<model.persistence.jooq.tables.records.CrawledRecord> getRecordType() {
		return model.persistence.jooq.tables.records.CrawledRecord.class;
	}

	/**
	 * The column <code>crawler.crawled.idcrawled</code>. 
	 */
	public final org.jooq.TableField<model.persistence.jooq.tables.records.CrawledRecord, java.lang.Integer> IDCRAWLED = createField("idcrawled", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>crawler.crawled.url</code>. 
	 */
	public final org.jooq.TableField<model.persistence.jooq.tables.records.CrawledRecord, java.lang.String> URL = createField("url", org.jooq.impl.SQLDataType.VARCHAR.length(450), this);

	/**
	 * The column <code>crawler.crawled.crawled</code>. 0 for not done; 1 for done.
	 */
	public final org.jooq.TableField<model.persistence.jooq.tables.records.CrawledRecord, java.lang.Integer> CRAWLED_ = createField("crawled", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * Create a <code>crawler.crawled</code> table reference
	 */
	public Crawled() {
		super("crawled", model.persistence.jooq.Crawler.CRAWLER);
	}

	/**
	 * Create an aliased <code>crawler.crawled</code> table reference
	 */
	public Crawled(java.lang.String alias) {
		super(alias, model.persistence.jooq.Crawler.CRAWLER, model.persistence.jooq.tables.Crawled.CRAWLED);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<model.persistence.jooq.tables.records.CrawledRecord, java.lang.Integer> getIdentity() {
		return model.persistence.jooq.Keys.IDENTITY_CRAWLED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<model.persistence.jooq.tables.records.CrawledRecord> getPrimaryKey() {
		return model.persistence.jooq.Keys.KEY_CRAWLED_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<model.persistence.jooq.tables.records.CrawledRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<model.persistence.jooq.tables.records.CrawledRecord>>asList(model.persistence.jooq.Keys.KEY_CRAWLED_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public model.persistence.jooq.tables.Crawled as(java.lang.String alias) {
		return new model.persistence.jooq.tables.Crawled(alias);
	}
}
