/**
 * This class is generated by jOOQ
 */
package model.persistence.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Data extends org.jooq.impl.TableImpl<model.persistence.jooq.tables.records.DataRecord> {

	private static final long serialVersionUID = -1966258851;

	/**
	 * The singleton instance of <code>crawler.data</code>
	 */
	public static final model.persistence.jooq.tables.Data DATA = new model.persistence.jooq.tables.Data();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<model.persistence.jooq.tables.records.DataRecord> getRecordType() {
		return model.persistence.jooq.tables.records.DataRecord.class;
	}

	/**
	 * The column <code>crawler.data.iddata</code>. 
	 */
	public final org.jooq.TableField<model.persistence.jooq.tables.records.DataRecord, java.lang.Integer> IDDATA = createField("iddata", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>crawler.data.origin</code>. 
	 */
	public final org.jooq.TableField<model.persistence.jooq.tables.records.DataRecord, java.lang.String> ORIGIN = createField("origin", org.jooq.impl.SQLDataType.VARCHAR.length(450), this);

	/**
	 * The column <code>crawler.data.data</code>. 
	 */
	public final org.jooq.TableField<model.persistence.jooq.tables.records.DataRecord, java.lang.String> DATA_ = createField("data", org.jooq.impl.SQLDataType.CLOB, this);

	/**
	 * Create a <code>crawler.data</code> table reference
	 */
	public Data() {
		super("data", model.persistence.jooq.Crawler.CRAWLER);
	}

	/**
	 * Create an aliased <code>crawler.data</code> table reference
	 */
	public Data(java.lang.String alias) {
		super(alias, model.persistence.jooq.Crawler.CRAWLER, model.persistence.jooq.tables.Data.DATA);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<model.persistence.jooq.tables.records.DataRecord, java.lang.Integer> getIdentity() {
		return model.persistence.jooq.Keys.IDENTITY_DATA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<model.persistence.jooq.tables.records.DataRecord> getPrimaryKey() {
		return model.persistence.jooq.Keys.KEY_DATA_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<model.persistence.jooq.tables.records.DataRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<model.persistence.jooq.tables.records.DataRecord>>asList(model.persistence.jooq.Keys.KEY_DATA_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public model.persistence.jooq.tables.Data as(java.lang.String alias) {
		return new model.persistence.jooq.tables.Data(alias);
	}
}
