/**
 * This class is generated by jOOQ
 */
package model.persistence.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CrawledRecord extends org.jooq.impl.UpdatableRecordImpl<model.persistence.jooq.tables.records.CrawledRecord> implements org.jooq.Record3<java.lang.Integer, java.lang.String, java.lang.Integer> {

	private static final long serialVersionUID = 1184611318;

	/**
	 * Setter for <code>crawler.crawled.idcrawled</code>. 
	 */
	public void setIdcrawled(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>crawler.crawled.idcrawled</code>. 
	 */
	public java.lang.Integer getIdcrawled() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>crawler.crawled.url</code>. 
	 */
	public void setUrl(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>crawler.crawled.url</code>. 
	 */
	public java.lang.String getUrl() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>crawler.crawled.crawled</code>. 0 for not done; 1 for done.
	 */
	public void setCrawled(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>crawler.crawled.crawled</code>. 0 for not done; 1 for done.
	 */
	public java.lang.Integer getCrawled() {
		return (java.lang.Integer) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.lang.String, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.lang.String, java.lang.Integer> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	public org.jooq.Field<java.lang.Integer> field1() {
		return model.persistence.jooq.tables.Crawled.CRAWLED.IDCRAWLED;
	}

	/**
	 * {@inheritDoc}
	 */
	public org.jooq.Field<java.lang.String> field2() {
		return model.persistence.jooq.tables.Crawled.CRAWLED.URL;
	}

	/**
	 * {@inheritDoc}
	 */
	public org.jooq.Field<java.lang.Integer> field3() {
		return model.persistence.jooq.tables.Crawled.CRAWLED.CRAWLED_;
	}

	/**
	 * {@inheritDoc}
	 */
	public java.lang.Integer value1() {
		return getIdcrawled();
	}

	/**
	 * {@inheritDoc}
	 */
	public java.lang.String value2() {
		return getUrl();
	}

	/**
	 * {@inheritDoc}
	 */
	public java.lang.Integer value3() {
		return getCrawled();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached CrawledRecord
	 */
	public CrawledRecord() {
		super(model.persistence.jooq.tables.Crawled.CRAWLED);
	}
}
