/**
 * This class is generated by jOOQ
 */
package model.persistence.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DataRecord extends org.jooq.impl.UpdatableRecordImpl<model.persistence.jooq.tables.records.DataRecord> implements org.jooq.Record3<java.lang.Integer, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = 388581566;

	/**
	 * Setter for <code>crawler.data.iddata</code>. 
	 */
	public void setIddata(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>crawler.data.iddata</code>. 
	 */
	public java.lang.Integer getIddata() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>crawler.data.origin</code>. 
	 */
	public void setOrigin(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>crawler.data.origin</code>. 
	 */
	public java.lang.String getOrigin() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>crawler.data.data</code>. 
	 */
	public void setData(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>crawler.data.data</code>. 
	 */
	public java.lang.String getData() {
		return (java.lang.String) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	public org.jooq.Field<java.lang.Integer> field1() {
		return model.persistence.jooq.tables.Data.DATA.IDDATA;
	}

	/**
	 * {@inheritDoc}
	 */
	public org.jooq.Field<java.lang.String> field2() {
		return model.persistence.jooq.tables.Data.DATA.ORIGIN;
	}

	/**
	 * {@inheritDoc}
	 */
	public org.jooq.Field<java.lang.String> field3() {
		return model.persistence.jooq.tables.Data.DATA.DATA_;
	}

	/**
	 * {@inheritDoc}
	 */
	public java.lang.Integer value1() {
		return getIddata();
	}

	/**
	 * {@inheritDoc}
	 */
	public java.lang.String value2() {
		return getOrigin();
	}

	/**
	 * {@inheritDoc}
	 */
	public java.lang.String value3() {
		return getData();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached DataRecord
	 */
	public DataRecord() {
		super(model.persistence.jooq.tables.Data.DATA);
	}
}
